services:
  - type: web
    name: medievaltype
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    customDomains:
      - devilishclover.space
    routes:
      - type: rewrite
        source: /*
        destination: /index.html